builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - linux
      - windows
    goarm:
      - "6"
      - "7"
    ldflags:
      - "-s -w"
      - "-X main.GitCommit={{ .Commit }}"
      - "-X main.GitVersion={{ .Version }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
